"""initial schema

Revision ID: 85ba1fb31caa
Revises: 
Create Date: 2026-08-08 15:23:23.301710

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renders custom column types by their fully qualified path
# (e.g. ``app.db.types.EncryptedText()``), so the package must be importable here.
import app.db.types
from sqlalchemy.dialects import postgresql

revision: str = '85ba1fb31caa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('size', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('screening_credits_used', sa.Integer(), nullable=False),
    sa.Column('screening_credits_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('data_retention_months', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('assessment_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_templates_deleted_at'), 'assessment_templates', ['deleted_at'], unique=False)
    op.create_index('ix_assessment_templates_org_active', 'assessment_templates', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_assessment_templates_organization_id'), 'assessment_templates', ['organization_id'], unique=False)
    op.create_table('email_accounts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=320), nullable=True),
    sa.Column('smtp_password', app.db.types.EncryptedText(), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('oauth_access_token', app.db.types.EncryptedText(), nullable=True),
    sa.Column('oauth_refresh_token', app.db.types.EncryptedText(), nullable=True),
    sa.Column('oauth_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warmup_status', sa.String(length=24), nullable=False),
    sa.Column('warmup_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('sent_today', sa.Integer(), nullable=False),
    sa.Column('sent_today_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reputation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('bounce_count', sa.Integer(), nullable=False),
    sa.Column('complaint_count', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_deleted_at'), 'email_accounts', ['deleted_at'], unique=False)
    op.create_index('ix_email_accounts_org_active', 'email_accounts', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_email_accounts_organization_id'), 'email_accounts', ['organization_id'], unique=False)
    op.create_index('uq_email_accounts_org_email', 'email_accounts', ['organization_id', 'email'], unique=True)
    op.create_table('message_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provider_template_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_deleted_at'), 'message_templates', ['deleted_at'], unique=False)
    op.create_index('ix_message_templates_org_active', 'message_templates', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_message_templates_organization_id'), 'message_templates', ['organization_id'], unique=False)
    op.create_index('ix_templates_org_channel', 'message_templates', ['organization_id', 'channel', 'deleted_at'], unique=False)
    op.create_table('offer_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('header_html', sa.Text(), nullable=True),
    sa.Column('footer_html', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_templates_deleted_at'), 'offer_templates', ['deleted_at'], unique=False)
    op.create_index('ix_offer_templates_org_active', 'offer_templates', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_offer_templates_organization_id'), 'offer_templates', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_org_active', 'users', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index('uq_users_org_email', 'users', ['organization_id', 'email'], unique=True)
    op.create_table('calendar_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', app.db.types.EncryptedText(), nullable=True),
    sa.Column('refresh_token', app.db.types.EncryptedText(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('working_hours', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_accounts_deleted_at'), 'calendar_accounts', ['deleted_at'], unique=False)
    op.create_index('ix_calendar_accounts_org_active', 'calendar_accounts', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_calendar_accounts_organization_id'), 'calendar_accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_calendar_accounts_user_id'), 'calendar_accounts', ['user_id'], unique=False)
    op.create_index('uq_calendar_user_provider', 'calendar_accounts', ['user_id', 'provider', 'email'], unique=True)
    op.create_table('candidates',
    sa.Column('full_name', app.db.types.EncryptedText(), nullable=False),
    sa.Column('email', app.db.types.EncryptedText(), nullable=False),
    sa.Column('email_index', sa.String(length=64), nullable=False),
    sa.Column('phone', app.db.types.EncryptedText(), nullable=True),
    sa.Column('phone_index', sa.String(length=64), nullable=True),
    sa.Column('location', app.db.types.EncryptedText(), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('seniority', sa.String(length=24), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('expected_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('skills_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_detail', sa.String(length=255), nullable=True),
    sa.Column('referred_by_id', sa.Uuid(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', app.db.types.EncryptedText(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_deleted_at'), 'candidates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_candidates_experience_years'), 'candidates', ['experience_years'], unique=False)
    op.create_index(op.f('ix_candidates_last_activity_at'), 'candidates', ['last_activity_at'], unique=False)
    op.create_index('ix_candidates_org_active', 'candidates', ['organization_id', 'deleted_at'], unique=False)
    op.create_index('ix_candidates_org_phone', 'candidates', ['organization_id', 'phone_index'], unique=False)
    op.create_index(op.f('ix_candidates_organization_id'), 'candidates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_candidates_source'), 'candidates', ['source'], unique=False)
    op.create_index('uq_candidates_org_email_idx', 'candidates', ['organization_id', 'email_index'], unique=True)
    op.create_table('jobs',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_mode', sa.String(length=16), nullable=False),
    sa.Column('employment_type', sa.String(length=24), nullable=False),
    sa.Column('seniority', sa.String(length=24), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('openings', sa.Integer(), nullable=False),
    sa.Column('min_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('max_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=False),
    sa.Column('requirements_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scoring_weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('auto_advance_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('auto_reject_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hiring_manager_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('bias_report_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_deleted_at'), 'jobs', ['deleted_at'], unique=False)
    op.create_index('ix_jobs_org_active', 'jobs', ['organization_id', 'deleted_at'], unique=False)
    op.create_index('ix_jobs_org_status', 'jobs', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('uq_jobs_org_slug', 'jobs', ['organization_id', 'slug'], unique=True)
    op.create_table('analytics',
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('applications', sa.Integer(), nullable=False),
    sa.Column('screenings', sa.Integer(), nullable=False),
    sa.Column('interviews', sa.Integer(), nullable=False),
    sa.Column('assessments', sa.Integer(), nullable=False),
    sa.Column('offers', sa.Integer(), nullable=False),
    sa.Column('hires', sa.Integer(), nullable=False),
    sa.Column('rejections', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('messages_opened', sa.Integer(), nullable=False),
    sa.Column('messages_replied', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_time_to_hire_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stage_counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_deleted_at'), 'analytics', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_analytics_job_id'), 'analytics', ['job_id'], unique=False)
    op.create_index('ix_analytics_org_active', 'analytics', ['organization_id', 'deleted_at'], unique=False)
    op.create_index('ix_analytics_org_date', 'analytics', ['organization_id', 'date'], unique=False)
    op.create_index(op.f('ix_analytics_organization_id'), 'analytics', ['organization_id'], unique=False)
    op.create_index('uq_analytics_org_job_date', 'analytics', ['organization_id', 'job_id', 'date'], unique=True)
    op.create_table('applications',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_detail', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('board_position', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_deleted_at'), 'applications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index('ix_applications_job_stage', 'applications', ['job_id', 'stage', 'deleted_at'], unique=False)
    op.create_index('ix_applications_org_active', 'applications', ['organization_id', 'deleted_at'], unique=False)
    op.create_index('ix_applications_org_stage', 'applications', ['organization_id', 'stage', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_applications_organization_id'), 'applications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_applications_score'), 'applications', ['score'], unique=False)
    op.create_index(op.f('ix_applications_source'), 'applications', ['source'], unique=False)
    op.create_index(op.f('ix_applications_stage'), 'applications', ['stage'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index('uq_applications_job_candidate', 'applications', ['job_id', 'candidate_id'], unique=True)
    op.create_table('candidate_consents',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('policy_version', sa.String(length=40), nullable=True),
    sa.Column('evidence_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_consents_candidate_id'), 'candidate_consents', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_consents_deleted_at'), 'candidate_consents', ['deleted_at'], unique=False)
    op.create_index('ix_candidate_consents_org_active', 'candidate_consents', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_candidate_consents_organization_id'), 'candidate_consents', ['organization_id'], unique=False)
    op.create_index('ix_consents_candidate_type', 'candidate_consents', ['candidate_id', 'consent_type', 'granted_at'], unique=False)
    op.create_table('job_board_postings',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('board', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_import_cursor', sa.String(length=255), nullable=True),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_board_postings_deleted_at'), 'job_board_postings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_job_board_postings_external_id'), 'job_board_postings', ['external_id'], unique=False)
    op.create_index(op.f('ix_job_board_postings_job_id'), 'job_board_postings', ['job_id'], unique=False)
    op.create_index('ix_job_board_postings_org_active', 'job_board_postings', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_job_board_postings_organization_id'), 'job_board_postings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_job_board_postings_status'), 'job_board_postings', ['status'], unique=False)
    op.create_index('ix_postings_org_board', 'job_board_postings', ['organization_id', 'board', 'status'], unique=False)
    op.create_index('uq_posting_job_board', 'job_board_postings', ['job_id', 'board'], unique=True)
    op.create_table('outreach_sequences',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('sender_account_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('send_window_start_hour', sa.Integer(), nullable=False),
    sa.Column('send_window_end_hour', sa.Integer(), nullable=False),
    sa.Column('send_on_weekends', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('stop_on_reply', sa.Boolean(), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_sequences_deleted_at'), 'outreach_sequences', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_outreach_sequences_job_id'), 'outreach_sequences', ['job_id'], unique=False)
    op.create_index('ix_outreach_sequences_org_active', 'outreach_sequences', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_outreach_sequences_organization_id'), 'outreach_sequences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outreach_sequences_status'), 'outreach_sequences', ['status'], unique=False)
    op.create_index('ix_sequences_org_status', 'outreach_sequences', ['organization_id', 'status', 'deleted_at'], unique=False)
    op.create_table('resumes',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parse_status', sa.String(length=24), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_model', sa.String(length=120), nullable=True),
    sa.Column('parse_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('raw_text', app.db.types.EncryptedText(), nullable=True),
    sa.Column('parsed_json', app.db.types.EncryptedJSON(), nullable=True),
    sa.Column('skills_extracted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('embedding_id', sa.String(length=120), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resumes_candidate', 'resumes', ['candidate_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_content_hash'), 'resumes', ['content_hash'], unique=False)
    op.create_index(op.f('ix_resumes_deleted_at'), 'resumes', ['deleted_at'], unique=False)
    op.create_index('ix_resumes_org_active', 'resumes', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_resumes_organization_id'), 'resumes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resumes_parse_status'), 'resumes', ['parse_status'], unique=False)
    op.create_table('assessments',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('responses_json', app.db.types.EncryptedJSON(), nullable=True),
    sa.Column('breakdown_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessments_application', 'assessments', ['application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assessments_application_id'), 'assessments', ['application_id'], unique=False)
    op.create_index(op.f('ix_assessments_deleted_at'), 'assessments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_assessments_invite_token'), 'assessments', ['invite_token'], unique=True)
    op.create_index('ix_assessments_org_active', 'assessments', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_assessments_organization_id'), 'assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_table('interviews',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('meeting_url', sa.String(length=1000), nullable=True),
    sa.Column('proposed_slots', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('booking_token', sa.String(length=64), nullable=True),
    sa.Column('booking_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_account_id', sa.Uuid(), nullable=True),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('reminder_24h_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_1h_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('rescheduled_from_id', sa.Uuid(), nullable=True),
    sa.Column('recording_url', sa.String(length=1000), nullable=True),
    sa.Column('transcript', app.db.types.EncryptedText(), nullable=True),
    sa.Column('analysis_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['calendar_account_id'], ['calendar_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['interviews.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interviews_application', 'interviews', ['application_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_interviews_booking_token'), 'interviews', ['booking_token'], unique=True)
    op.create_index(op.f('ix_interviews_deleted_at'), 'interviews', ['deleted_at'], unique=False)
    op.create_index('ix_interviews_org_active', 'interviews', ['organization_id', 'deleted_at'], unique=False)
    op.create_index('ix_interviews_org_scheduled', 'interviews', ['organization_id', 'scheduled_at', 'status'], unique=False)
    op.create_index(op.f('ix_interviews_organization_id'), 'interviews', ['organization_id'], unique=False)
    op.create_index(op.f('ix_interviews_scheduled_at'), 'interviews', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_table('offer_letters',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('salary', app.db.types.EncryptedText(), nullable=True),
    sa.Column('salary_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=False),
    sa.Column('salary_period', sa.String(length=16), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('equity', sa.String(length=255), nullable=True),
    sa.Column('benefits_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('reporting_manager', sa.String(length=255), nullable=True),
    sa.Column('work_location', sa.String(length=255), nullable=True),
    sa.Column('rendered_body', app.db.types.EncryptedText(), nullable=True),
    sa.Column('document_path', sa.String(length=1000), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('esign_provider', sa.String(length=32), nullable=True),
    sa.Column('esign_envelope_id', sa.String(length=255), nullable=True),
    sa.Column('esign_status', sa.String(length=40), nullable=True),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['offer_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_letters_access_token'), 'offer_letters', ['access_token'], unique=True)
    op.create_index(op.f('ix_offer_letters_application_id'), 'offer_letters', ['application_id'], unique=False)
    op.create_index(op.f('ix_offer_letters_deleted_at'), 'offer_letters', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_offer_letters_esign_envelope_id'), 'offer_letters', ['esign_envelope_id'], unique=False)
    op.create_index('ix_offer_letters_org_active', 'offer_letters', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_offer_letters_organization_id'), 'offer_letters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_offer_letters_status'), 'offer_letters', ['status'], unique=False)
    op.create_index('ix_offers_application', 'offer_letters', ['application_id', 'created_at'], unique=False)
    op.create_index('ix_offers_org_status', 'offer_letters', ['organization_id', 'status', 'deleted_at'], unique=False)
    op.create_table('screenings',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('skill_match', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('education_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cultural_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weights_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('matched_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('missing_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('strengths', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('concerns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('engine', sa.String(length=24), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_screenings_application', 'screenings', ['application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_screenings_application_id'), 'screenings', ['application_id'], unique=False)
    op.create_index(op.f('ix_screenings_deleted_at'), 'screenings', ['deleted_at'], unique=False)
    op.create_index('ix_screenings_org_active', 'screenings', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_screenings_organization_id'), 'screenings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_screenings_overall_score'), 'screenings', ['overall_score'], unique=False)
    op.create_table('sequence_enrollments',
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('next_send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['outreach_sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enrollments_due', 'sequence_enrollments', ['status', 'next_send_at'], unique=False)
    op.create_index(op.f('ix_sequence_enrollments_candidate_id'), 'sequence_enrollments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_sequence_enrollments_deleted_at'), 'sequence_enrollments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sequence_enrollments_next_send_at'), 'sequence_enrollments', ['next_send_at'], unique=False)
    op.create_index('ix_sequence_enrollments_org_active', 'sequence_enrollments', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_sequence_enrollments_organization_id'), 'sequence_enrollments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sequence_enrollments_sequence_id'), 'sequence_enrollments', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_sequence_enrollments_status'), 'sequence_enrollments', ['status'], unique=False)
    op.create_index('uq_enrollment', 'sequence_enrollments', ['sequence_id', 'candidate_id'], unique=True)
    op.create_table('sequence_steps',
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('delay_hours', sa.Integer(), nullable=False),
    sa.Column('variant_group', sa.String(length=16), nullable=True),
    sa.Column('subject_override', sa.String(length=500), nullable=True),
    sa.Column('body_override', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['outreach_sequences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_steps_deleted_at'), 'sequence_steps', ['deleted_at'], unique=False)
    op.create_index('ix_sequence_steps_org_active', 'sequence_steps', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_sequence_steps_organization_id'), 'sequence_steps', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sequence_steps_sequence_id'), 'sequence_steps', ['sequence_id'], unique=False)
    op.create_index('uq_step_order', 'sequence_steps', ['sequence_id', 'step_order'], unique=True)
    op.create_table('stage_events',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage', sa.String(length=24), nullable=True),
    sa.Column('to_stage', sa.String(length=24), nullable=False),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('seconds_in_previous_stage', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stage_events_application', 'stage_events', ['application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stage_events_application_id'), 'stage_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_stage_events_deleted_at'), 'stage_events', ['deleted_at'], unique=False)
    op.create_index('ix_stage_events_org_active', 'stage_events', ['organization_id', 'deleted_at'], unique=False)
    op.create_index('ix_stage_events_org_to', 'stage_events', ['organization_id', 'to_stage', 'created_at'], unique=False)
    op.create_index(op.f('ix_stage_events_organization_id'), 'stage_events', ['organization_id'], unique=False)
    op.create_table('interview_participants',
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_organizer', sa.Boolean(), nullable=False),
    sa.Column('response_status', sa.String(length=24), nullable=False),
    sa.Column('rating', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('recommendation', sa.String(length=32), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('feedback_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scorecard_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_participants_deleted_at'), 'interview_participants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_interview_participants_interview_id'), 'interview_participants', ['interview_id'], unique=False)
    op.create_index('ix_interview_participants_org_active', 'interview_participants', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_interview_participants_organization_id'), 'interview_participants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_interview_participants_user_id'), 'interview_participants', ['user_id'], unique=False)
    op.create_index('uq_participant', 'interview_participants', ['interview_id', 'user_id'], unique=True)
    op.create_table('outreach_messages',
    sa.Column('enrollment_id', sa.Uuid(), nullable=True),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('email_account_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('to_address', app.db.types.EncryptedText(), nullable=False),
    sa.Column('subject', app.db.types.EncryptedText(), nullable=True),
    sa.Column('body', app.db.types.EncryptedText(), nullable=True),
    sa.Column('variant_group', sa.String(length=16), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('tracking_token', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['sequence_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['sequence_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_enrollment', 'outreach_messages', ['enrollment_id', 'created_at'], unique=False)
    op.create_index('ix_messages_org_status', 'outreach_messages', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_outreach_messages_candidate_id'), 'outreach_messages', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_outreach_messages_deleted_at'), 'outreach_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_outreach_messages_enrollment_id'), 'outreach_messages', ['enrollment_id'], unique=False)
    op.create_index('ix_outreach_messages_org_active', 'outreach_messages', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_outreach_messages_organization_id'), 'outreach_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outreach_messages_provider_message_id'), 'outreach_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_outreach_messages_status'), 'outreach_messages', ['status'], unique=False)
    op.create_index(op.f('ix_outreach_messages_tracking_token'), 'outreach_messages', ['tracking_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_messages_tracking_token'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_status'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_provider_message_id'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_organization_id'), table_name='outreach_messages')
    op.drop_index('ix_outreach_messages_org_active', table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_enrollment_id'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_deleted_at'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_candidate_id'), table_name='outreach_messages')
    op.drop_index('ix_messages_org_status', table_name='outreach_messages')
    op.drop_index('ix_messages_enrollment', table_name='outreach_messages')
    op.drop_table('outreach_messages')
    op.drop_index('uq_participant', table_name='interview_participants')
    op.drop_index(op.f('ix_interview_participants_user_id'), table_name='interview_participants')
    op.drop_index(op.f('ix_interview_participants_organization_id'), table_name='interview_participants')
    op.drop_index('ix_interview_participants_org_active', table_name='interview_participants')
    op.drop_index(op.f('ix_interview_participants_interview_id'), table_name='interview_participants')
    op.drop_index(op.f('ix_interview_participants_deleted_at'), table_name='interview_participants')
    op.drop_table('interview_participants')
    op.drop_index(op.f('ix_stage_events_organization_id'), table_name='stage_events')
    op.drop_index('ix_stage_events_org_to', table_name='stage_events')
    op.drop_index('ix_stage_events_org_active', table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_deleted_at'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_application_id'), table_name='stage_events')
    op.drop_index('ix_stage_events_application', table_name='stage_events')
    op.drop_table('stage_events')
    op.drop_index('uq_step_order', table_name='sequence_steps')
    op.drop_index(op.f('ix_sequence_steps_sequence_id'), table_name='sequence_steps')
    op.drop_index(op.f('ix_sequence_steps_organization_id'), table_name='sequence_steps')
    op.drop_index('ix_sequence_steps_org_active', table_name='sequence_steps')
    op.drop_index(op.f('ix_sequence_steps_deleted_at'), table_name='sequence_steps')
    op.drop_table('sequence_steps')
    op.drop_index('uq_enrollment', table_name='sequence_enrollments')
    op.drop_index(op.f('ix_sequence_enrollments_status'), table_name='sequence_enrollments')
    op.drop_index(op.f('ix_sequence_enrollments_sequence_id'), table_name='sequence_enrollments')
    op.drop_index(op.f('ix_sequence_enrollments_organization_id'), table_name='sequence_enrollments')
    op.drop_index('ix_sequence_enrollments_org_active', table_name='sequence_enrollments')
    op.drop_index(op.f('ix_sequence_enrollments_next_send_at'), table_name='sequence_enrollments')
    op.drop_index(op.f('ix_sequence_enrollments_deleted_at'), table_name='sequence_enrollments')
    op.drop_index(op.f('ix_sequence_enrollments_candidate_id'), table_name='sequence_enrollments')
    op.drop_index('ix_enrollments_due', table_name='sequence_enrollments')
    op.drop_table('sequence_enrollments')
    op.drop_index(op.f('ix_screenings_overall_score'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_organization_id'), table_name='screenings')
    op.drop_index('ix_screenings_org_active', table_name='screenings')
    op.drop_index(op.f('ix_screenings_deleted_at'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_application_id'), table_name='screenings')
    op.drop_index('ix_screenings_application', table_name='screenings')
    op.drop_table('screenings')
    op.drop_index('ix_offers_org_status', table_name='offer_letters')
    op.drop_index('ix_offers_application', table_name='offer_letters')
    op.drop_index(op.f('ix_offer_letters_status'), table_name='offer_letters')
    op.drop_index(op.f('ix_offer_letters_organization_id'), table_name='offer_letters')
    op.drop_index('ix_offer_letters_org_active', table_name='offer_letters')
    op.drop_index(op.f('ix_offer_letters_esign_envelope_id'), table_name='offer_letters')
    op.drop_index(op.f('ix_offer_letters_deleted_at'), table_name='offer_letters')
    op.drop_index(op.f('ix_offer_letters_application_id'), table_name='offer_letters')
    op.drop_index(op.f('ix_offer_letters_access_token'), table_name='offer_letters')
    op.drop_table('offer_letters')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_scheduled_at'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_organization_id'), table_name='interviews')
    op.drop_index('ix_interviews_org_scheduled', table_name='interviews')
    op.drop_index('ix_interviews_org_active', table_name='interviews')
    op.drop_index(op.f('ix_interviews_deleted_at'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_booking_token'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_index('ix_interviews_application', table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_organization_id'), table_name='assessments')
    op.drop_index('ix_assessments_org_active', table_name='assessments')
    op.drop_index(op.f('ix_assessments_invite_token'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_deleted_at'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_application_id'), table_name='assessments')
    op.drop_index('ix_assessments_application', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_resumes_parse_status'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_organization_id'), table_name='resumes')
    op.drop_index('ix_resumes_org_active', table_name='resumes')
    op.drop_index(op.f('ix_resumes_deleted_at'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_content_hash'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_index('ix_resumes_candidate', table_name='resumes')
    op.drop_table('resumes')
    op.drop_index('ix_sequences_org_status', table_name='outreach_sequences')
    op.drop_index(op.f('ix_outreach_sequences_status'), table_name='outreach_sequences')
    op.drop_index(op.f('ix_outreach_sequences_organization_id'), table_name='outreach_sequences')
    op.drop_index('ix_outreach_sequences_org_active', table_name='outreach_sequences')
    op.drop_index(op.f('ix_outreach_sequences_job_id'), table_name='outreach_sequences')
    op.drop_index(op.f('ix_outreach_sequences_deleted_at'), table_name='outreach_sequences')
    op.drop_table('outreach_sequences')
    op.drop_index('uq_posting_job_board', table_name='job_board_postings')
    op.drop_index('ix_postings_org_board', table_name='job_board_postings')
    op.drop_index(op.f('ix_job_board_postings_status'), table_name='job_board_postings')
    op.drop_index(op.f('ix_job_board_postings_organization_id'), table_name='job_board_postings')
    op.drop_index('ix_job_board_postings_org_active', table_name='job_board_postings')
    op.drop_index(op.f('ix_job_board_postings_job_id'), table_name='job_board_postings')
    op.drop_index(op.f('ix_job_board_postings_external_id'), table_name='job_board_postings')
    op.drop_index(op.f('ix_job_board_postings_deleted_at'), table_name='job_board_postings')
    op.drop_table('job_board_postings')
    op.drop_index('ix_consents_candidate_type', table_name='candidate_consents')
    op.drop_index(op.f('ix_candidate_consents_organization_id'), table_name='candidate_consents')
    op.drop_index('ix_candidate_consents_org_active', table_name='candidate_consents')
    op.drop_index(op.f('ix_candidate_consents_deleted_at'), table_name='candidate_consents')
    op.drop_index(op.f('ix_candidate_consents_candidate_id'), table_name='candidate_consents')
    op.drop_table('candidate_consents')
    op.drop_index('uq_applications_job_candidate', table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_stage'), table_name='applications')
    op.drop_index(op.f('ix_applications_source'), table_name='applications')
    op.drop_index(op.f('ix_applications_score'), table_name='applications')
    op.drop_index(op.f('ix_applications_organization_id'), table_name='applications')
    op.drop_index('ix_applications_org_stage', table_name='applications')
    op.drop_index('ix_applications_org_active', table_name='applications')
    op.drop_index('ix_applications_job_stage', table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_deleted_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index('uq_analytics_org_job_date', table_name='analytics')
    op.drop_index(op.f('ix_analytics_organization_id'), table_name='analytics')
    op.drop_index('ix_analytics_org_date', table_name='analytics')
    op.drop_index('ix_analytics_org_active', table_name='analytics')
    op.drop_index(op.f('ix_analytics_job_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_deleted_at'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index('uq_jobs_org_slug', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_index('ix_jobs_org_status', table_name='jobs')
    op.drop_index('ix_jobs_org_active', table_name='jobs')
    op.drop_index(op.f('ix_jobs_deleted_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('uq_candidates_org_email_idx', table_name='candidates')
    op.drop_index(op.f('ix_candidates_source'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_organization_id'), table_name='candidates')
    op.drop_index('ix_candidates_org_phone', table_name='candidates')
    op.drop_index('ix_candidates_org_active', table_name='candidates')
    op.drop_index(op.f('ix_candidates_last_activity_at'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_experience_years'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_deleted_at'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('uq_calendar_user_provider', table_name='calendar_accounts')
    op.drop_index(op.f('ix_calendar_accounts_user_id'), table_name='calendar_accounts')
    op.drop_index(op.f('ix_calendar_accounts_organization_id'), table_name='calendar_accounts')
    op.drop_index('ix_calendar_accounts_org_active', table_name='calendar_accounts')
    op.drop_index(op.f('ix_calendar_accounts_deleted_at'), table_name='calendar_accounts')
    op.drop_table('calendar_accounts')
    op.drop_index('uq_users_org_email', table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index('ix_users_org_active', table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_offer_templates_organization_id'), table_name='offer_templates')
    op.drop_index('ix_offer_templates_org_active', table_name='offer_templates')
    op.drop_index(op.f('ix_offer_templates_deleted_at'), table_name='offer_templates')
    op.drop_table('offer_templates')
    op.drop_index('ix_templates_org_channel', table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_organization_id'), table_name='message_templates')
    op.drop_index('ix_message_templates_org_active', table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_deleted_at'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index('uq_email_accounts_org_email', table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_organization_id'), table_name='email_accounts')
    op.drop_index('ix_email_accounts_org_active', table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_deleted_at'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_index(op.f('ix_assessment_templates_organization_id'), table_name='assessment_templates')
    op.drop_index('ix_assessment_templates_org_active', table_name='assessment_templates')
    op.drop_index(op.f('ix_assessment_templates_deleted_at'), table_name='assessment_templates')
    op.drop_table('assessment_templates')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
